version: "3.8"

services:
    react-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: realstate
        ports:
            - "3000:80"
        restart: always
        volumes:
            - /app/node_modules
