server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # ⬅️ **التعديل هنا (النقطة الأهم)**
    location / {
        try_files $uri $uri/ /index.html;
    }
    # ➡️ هذا يعني: حاول إيجاد الملف المطلوب ($uri)، ثم حاول إيجاد دليل بهذا الاسم ($uri/)، وإذا لم تجد أياً منهما، قم بتقديم الملف /index.html.

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name realestatemerchants.app;

    ssl_certificate /etc/letsencrypt/live/realestatemerchants.app/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/realestatemerchants.app/privkey.pem;

    location / {
        proxy_pass http://app:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}